const colors = [
  'aqua',
  'azure',
  'beige',
  'black',
  'blue',
  'brown',
  'coral',
  'cyan',
  'gold',
  'gray',
  'green',
  'ivory',
  'khaki',
  'lime',
  'keylime',
  'linen',
  'maroon',
  'navy',
  'olive',
  'orange',
  'peach',
  'pink',
  'plum',
  'purple',
  'red',
  'salmon',
  'silver',
  'tan',
  'teal',
  'tomato',
  'violet',
  'white',
  'yellow',
  'indigo',
  'saffron',
  'golden',
  'mustard',
  'amber',
];

const cuteAnimalNames = [
  'bunny',
  'puppy',
  'kitten',
  'chipmunk',
  'hedgehog',
  'dolphin',
  'seal',
  'turtle',
  'penguin',
  'parrot',
  'hummingbird',
  'rabbit',
  'squirrel',
  'butterfly',
  'dragonfly',
  'ladybug',
  'goldfish',
  'puppyfish',
  'guppy',
  'hamster',
  'gerbil',
  'hare',
  'ferret',
  'chinchilla',
];

const qualities = [
  'kind',
  'honest',
  'courageous',
  'humorous',
  'gracious',
  'witty',
  'charming',
  'passionate',
  'empathetic',
  'patient',
  'optimistic',
  'joyful',
  'loving',
  'peaceful',
  'serene',
  'wise',
  'strong',
  'resilient',
  'awesome',
  'funny',
  'grateful',
  'humble',
  'curious',
  'super',
  'courteous',
  'smart',
  'genius',
  'brave',
  'quick',
  'enigmatic',
  'friendly',
  'clever',
  'chill',
  'calm',
];

const createRandomName = () => {
  const randomColor = Math.floor(Math.random() * colors.length);
  const randomAnimal = Math.floor(Math.random() * cuteAnimalNames.length);
  const randomQuality = Math.floor(Math.random() * qualities.length);
  return (colors[randomColor] + '-' + qualities[randomQuality] + '-' +
    cuteAnimalNames[randomAnimal]);
};

export default createRandomName;
